# Stage 5: Corridor Complex (Enhanced HD)
# Vision offset: 0.2m ahead, Grid resolution: 0.1m (2x better), tighter spacing, more challenging

simulation:
  corridor_length: 100.0
  corridor_width: 3.0
  robot_view_range: 4.0
  max_steps: 30000
  env_precision: 0.1  # HD: 2x better resolution
  vision_position_offset: 0.2  # Vision centered 0.2m ahead
  vision_encoding_mode: "binary_with_robot"  # Show robot position
  warmup_steps: 1000
  action_repeat: 5
  num_envs: 8
  obstacles_mode: "sinusoidal"
  obstacles_mode_param:
    obstacle_sep: 5.0  # Tighter spacing
    obstacle_size_x: 0.4
    obstacle_size_y: 0.4
    obstacle_size_z: 0.5
  gravity: "0 0 -0.20"
  dt: 0.01
  solver: "Newton"
  iterations: 500
  ground_friction: "1 0.005 0.0001"

robot:
  xml_path: "xml/four_wheels_robot.xml"
  action_smoothing_k: 5
  control_mode: "discrete_direction"
  max_speed: 10.0

model:
  type: "mlp"
  input_mode: "single_head"
  state_history_length: 4
  include_goal: true
  embedding_dim: 64
  hidden_sizes: [256, 256]

rewards:
  type: "velocity"
  goal: 100.0
  use_velocity_reward: true
  use_true_velocity: true
  velocity_reward_scale: 5.0
  forward_progress_scale: 10.0
  stuck_penalty: -0.2
  stuck_x_velocity_threshold: 0.03
  collision: -3.0

training:
  agent_type: "ppo"
  learning_rate: 0.0001
  gamma: 0.99
  k_epochs: 4
  eps_clip: 0.1
  update_timestep: 2048
  gae_lambda: 0.95
  entropy_coeff: 0.005
  value_loss_coeff: 0.5
  grad_clip_max_norm: 0.5
  reward_scale: 1.0
